# Generated by Django 4.2.20 on 2025-05-06 11:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('office_number', models.CharField(max_length=10, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Врача',
                'verbose_name_plural': 'Врачи',
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('patient_address', models.CharField(max_length=100, verbose_name='Адрес проживания')),
            ],
            options={
                'verbose_name': 'Пациента',
                'verbose_name_plural': 'Пациенты',
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateField(verbose_name='Дата')),
                ('time_reception', models.TimeField(verbose_name='Время')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stomatology.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stomatology.patient')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
                'db_table': 'reception',
                'ordering': [-1],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Услуга')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Service_rendered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('number_reception', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stomatology.reception')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stomatology.service')),
            ],
            options={
                'verbose_name': 'Оказанную услугу',
                'verbose_name_plural': 'Оказанные услуги',
                'db_table': 'service_rendered',
                'ordering': [-1],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.PositiveIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_reception', models.TimeField(verbose_name='Начало приема')),
                ('end_reception', models.TimeField(verbose_name='Конец приема')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stomatology.doctor')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание работы врачей',
                'db_table': 'shedule',
            },
        ),
    ]
